apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-producer
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: eminoz/rb
          imagePullPolicy: Always # Always pull the latest image
          ports:
            - containerPort: 80
---
