apiVersion: v1
kind: Service
metadata:
  name: rabbit-producer
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer